POST http://localhost:7071/api/sentimentAnalysis
# POST https://jehollan-europydev.azurewebsites.net/api/analysesentiment
Content-Type: application/json

# {
#     "name": "harish"
# }


{
    "url": "https://wishuappblob.blob.core.windows.net/surveyed/6peVx0cq2bQmpTvi6oBio9nCU4p2_86d523b3-a9f3-033e-9c50-a166ef48f9b5.mp4"
}